const express = require('express');
const cors = require('cors');
const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const archiver = require('archiver');
const kyroAI = require('../../../packages/kyro-ai/engine.js');

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// MongoDB connection
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/kyro';
mongoose.connect(MONGODB_URI)
  .then(() => console.log('✅ Connected to MongoDB'))
  .catch(err => console.error('❌ MongoDB connection error:', err));

const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Kyro API',
      version: '0.0.1',
      description: 'Kyro AI Website Generator API',
    },
    servers: [
      {
        url: 'http://localhost:3001',
        description: 'Development server',
      },
    ],
  },
  apis: ['./src/index.js'],
};

const swaggerSpec = swaggerJsdoc(swaggerOptions);

app.get('/api-docs.json', (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(swaggerSpec);
});

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, {
  swaggerOptions: {
    url: '/api-docs.json'
  }
}));

const GENERATED_PROJECTS_DIR = path.join(__dirname, '..', 'generated-projects');
const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');
const PROJECTS_METADATA = new Map();

const generateProjectId = () => {
  const timestamp = Date.now();
  const random = crypto.randomBytes(4).toString('hex');
  return `project-${timestamp}-${random}`;
};

const readTemplate = (templateName) => {
  const templatePath = path.join(TEMPLATES_DIR, templateName);
  return fs.readFileSync(templatePath, 'utf-8');
};

const ensureDir = (dirPath) => {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    console.log(`Created directory: ${dirPath}`);
  }
};

const writeFile = (filePath, content) => {
  const dir = path.dirname(filePath);
  ensureDir(dir);
  fs.writeFileSync(filePath, content);
  console.log(`Created file: ${filePath}`);
};

const createPackageJson = (projectId, websiteType) => {
  return JSON.stringify({
    name: `generated-app-${projectId}`,
    version: '1.0.0',
    description: `Generated ${websiteType} website`,
    main: 'backend/index.js',
    scripts: {
      start: 'node backend/index.js',
    },
    dependencies: {
      express: '^4.18.0',
      mongoose: '^9.6.1',
      bcryptjs: '^3.0.3',
      jsonwebtoken: '^9.0.0',
    },
  }, null, 2);
};

const createReadme = (projectId, websiteType, features) => {
  return `# Generated Project: ${projectId}\n\nGenerated by Kyro AI Engine\n\n## Website Type\n${websiteType}\n\n## Features\n${features.join(', ')}\n\n## Structure\n- frontend/\n- backend/\n- package.json\n- README.md\n`;
};

const getBackendIndex = (features) => {
  const hasAuth = features.includes('auth');
  const hasPayments = features.includes('payments');
  
  let content = `const express = require('express');\nconst cors = require('cors');\nconst mongoose = require('mongoose');\n\nconst app = express();\napp.use(cors());\napp.use(express.json());\n\n`;
  
  if (hasAuth) {
    content += `const authRoutes = require('./routes/auth.routes.js');\napp.use('/api/auth', authRoutes);\n\n`;
  }
    
  if (hasPayments) {
    content += `const paymentRoutes = require('./routes/payment.routes.js');\napp.use('/api/payments', paymentRoutes);\n\n`;
  }
    
  content += `app.listen(3001, () => {\n  console.log('Backend running on port 3001');\n});\n`;
  return content;
};

// Mongoose schemas
const userSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
});

const projectSchema = new mongoose.Schema({
  projectId: { type: String, required: true, unique: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  projectName: { type: String },
  websiteType: { type: String, required: true },
  features: [String],
  modules: [String],
  structure: [String],
  downloadPath: String,
  createdAt: { type: Date, default: Date.now },
});

const User = mongoose.model('User', userSchema);
const Project = mongoose.model('Project', projectSchema);

const JWT_SECRET = process.env.JWT_SECRET || 'kyro-secret-key-2024';

const generateToken = (user) => {
  return jwt.sign(
    { id: user.id, username: user.username, email: user.email },
    JWT_SECRET,
    { expiresIn: '7d' }
  );
};

const authMiddleware = (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader) {
      return res.status(401).json({ success: false, error: 'No token provided' });
    }

    const token = authHeader.split(' ')[1];
    if (!token) {
      return res.status(401).json({ success: false, error: 'No token provided' });
    }

    const decoded = jwt.verify(token, JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ success: false, error: 'Invalid token' });
  }
};

/**
 * @openapi
 * /auth/signup:
 *   post:
 *     summary: User signup
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [username, email, password]
 *             properties:
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: User created successfully
 */
app.post('/auth/signup', async (req, res) => {
  try {
    const { username, email, password } = req.body;

    if (!username || !email || !password) {
      return res.status(400).json({ success: false, error: 'Missing required fields' });
    }

    const existingUser = await User.findOne({ $or: [{ email }, { username }] });
    if (existingUser) {
      return res.status(400).json({ success: false, error: 'User already exists' });
    }

    const hashedPassword = bcrypt.hashSync(password, 10);
    const user = new User({ username, email, password: hashedPassword });
    await user.save();

    const token = generateToken({ id: user._id.toString(), username: user.username, email: user.email });

    res.json({
      success: true,
      data: {
        token,
        user: { id: user._id, username: user.username, email: user.email },
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

/**
 * @openapi
 * /auth/login:
 *   post:
 *     summary: User login
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password]
 *             properties:
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Login successful
 */
app.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ success: false, error: 'Missing required fields' });
    }

    const user = await User.findOne({ email });
    if (!user || !bcrypt.compareSync(password, user.password)) {
      return res.status(401).json({ success: false, error: 'Invalid credentials' });
    }

    const token = generateToken({ id: user._id.toString(), username: user.username, email: user.email });

    res.json({
      success: true,
      data: {
        token,
        user: { id: user._id, username: user.username, email: user.email },
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

/**
 * @openapi
 * /generate:
 *   post:
 *     summary: Generate project structure
 *     description: Generates a project with files based on website type and features
 *     tags: [Generator]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [websiteType, features]
 *             properties:
 *               websiteType:
 *                 type: string
 *                 enum: [basic, ecommerce, social, blog]
 *                 example: ecommerce
 *               features:
 *                 type: array
 *                 items:
 *                   type: string
 *                   enum: [auth, payments, admin]
 *                 example: [auth, payments]
 *               projectName:
 *                 type: string
 *                 example: My Awesome Website
 *     responses:
 *       200:
 *         description: Successfully generated project structure
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     projectId:
 *                       type: string
 *                     projectName:
 *                       type: string
 *                     downloadPath:
 *                       type: string
 *                     previewUrl:
 *                       type: string
 *                     structure:
 *                       type: array
 *                       items:
 *                         type: string
 *                     modules:
 *                       type: array
 *                       items:
 *                         type: string
 *       400:
 *         description: Missing required fields
 */
app.post('/generate', authMiddleware, async (req, res) => {
  try {
    const { websiteType, features, projectName } = req.body;

    if (!websiteType || !features) {
      const response = {
        success: false,
        error: 'Missing required fields: websiteType and features'
      };
      return res.status(400).json(response);
    }

    const projectId = generateProjectId();
    const basePath = path.join(GENERATED_PROJECTS_DIR, projectId);
    const structure = [];

    console.log(`\n🤖 Kyro AI Engine: Generating project ${projectId}`);
    console.log(`📂 Location: ${basePath}`);

    // Step 1: AI Engine generates the plan
    const userConfig = { websiteType, features, techPreferences: {} };
    const plan = kyroAI.generatePlan(userConfig);

    console.log(`📋 Generation Plan:`);
    console.log(`   Website Type: ${plan.websiteType}`);
    console.log(`   Resolved Features: ${plan.resolvedFeatures.join(', ')}`);
    console.log(`   Modules: ${plan.modules.map(m => m.name).join(', ')}`);

    ensureDir(basePath);
    structure.push('frontend/');
    structure.push('backend/');

    const backendPath = path.join(basePath, 'backend');
    ensureDir(backendPath);

    // Step 2: Generator writes files based on plan
    plan.modules.forEach((module) => {
      console.log(`  📦 Processing module: ${module.name}`);
      module.files.forEach((file) => {
        const filePath = path.join(basePath, file.path);
        const content = readTemplate(file.template);
        writeFile(filePath, content);
        structure.push(file.path);
      });
    });

    // Generate backend index
    const indexPath = path.join(backendPath, 'index.js');
    writeFile(indexPath, getBackendIndex(features));
    structure.push('backend/index.js');

    // Generate package.json and README
    const packageJsonPath = path.join(basePath, 'package.json');
    writeFile(packageJsonPath, createPackageJson(projectId, websiteType));
    structure.push('package.json');

    const readmePath = path.join(basePath, 'README.md');
    writeFile(readmePath, createReadme(projectId, websiteType, features));
    structure.push('README.md');

    structure.push('frontend/');

    // Save project to database
    const project = new Project({
      projectId,
      userId: req.user.id,
      projectName: projectName || `Project ${projectId}`,
      websiteType,
      features,
      modules: plan.modules.map(m => m.name),
      structure,
      downloadPath: basePath
    });
    await project.save();

    // Store project metadata
    const metadata = {
      projectId,
      projectName: projectName || `Project ${projectId}`,
      websiteType,
      features,
      modules: plan.modules.map(m => m.name),
      structure,
      downloadPath: basePath,
      previewUrl: `/preview/${projectId}`,
      createdAt: new Date().toISOString()
    };
    PROJECTS_METADATA.set(projectId, metadata);

    console.log(`✅ Project ${projectId} generated successfully via AI Engine!\n`);

    const response = {
      success: true,
      data: {
        projectId,
        projectName: projectName || `Project ${projectId}`,
        downloadPath: basePath,
        previewUrl: `/preview/${projectId}`,
        structure,
        modules: plan.modules.map(m => m.name),
        message: `Project generated using AI Engine. Modules: ${plan.modules.map(m => m.name).join(', ')}`
      }
    };

    res.json(response);
  } catch (error) {
    console.error(`❌ Error generating project:`, error.message);
    const response = {
      success: false,
      error: error.message
    };
    res.status(500).json(response);
  }
});

/**
 * @openapi
 * /download/{projectId}:
 *   get:
 *     summary: Download generated project as ZIP
 *     description: Compresses the project folder and returns a downloadable ZIP file
 *     tags: [Download]
 *     parameters:
 *       - in: path
 *         name: projectId
 *         required: true
 *         schema:
 *           type: string
 *         description: The project ID to download
 *     responses:
 *       200:
 *         description: ZIP file download
 *         content:
 *           application/zip:
 *             schema:
 *               type: string
 *               format: binary
 *       404:
 *         description: Project not found
 */
app.get('/download/:projectId', (req, res) => {
  try {
    const { projectId } = req.params;
    const projectPath = path.join(GENERATED_PROJECTS_DIR, projectId);

    if (!fs.existsSync(projectPath)) {
      return res.status(404).json({ success: false, error: `Project ${projectId} not found` });
    }

    const zipFileName = `kyro-project-${projectId}.zip`;
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename=${zipFileName}`);

    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => {
      console.error(`❌ Archive error:`, err.message);
      res.status(500).json({ success: false, error: 'Failed to create ZIP file' });
    });

    archive.on('end', () => {
      console.log(`✅ Download completed: ${zipFileName} (${archive.pointer()} bytes)`);
    });

    archive.pipe(res);
    archive.directory(projectPath, false);
    archive.finalize();
  } catch (error) {
    console.error('Download error:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

/**
 * @openapi
 * /project/{projectId}:
 *   get:
 *     summary: Get project metadata
 *     description: Returns full project metadata and structure
 *     tags: [Project]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: projectId
 *         required: true
 *         schema:
 *           type: string
 *         description: The project ID
 *     responses:
 *       200:
 *         description: Project metadata
 *       404:
 *         description: Project not found
 */
app.get('/project/:projectId', authMiddleware, async (req, res) => {
  try {
    const { projectId } = req.params;

    console.log(`\n🔍 Metadata request for project: ${projectId}`);

    const project = await Project.findOne({ projectId, userId: req.user.id });
    if (!project) {
      return res.status(404).json({ success: false, error: `Project ${projectId} not found` });
    }

    const metadata = PROJECTS_METADATA.get(projectId) || {
      projectId: project.projectId,
      projectName: project.projectName || `Project ${projectId}`,
      websiteType: project.websiteType,
      features: project.features,
      modules: project.modules,
      structure: project.structure,
      downloadPath: project.downloadPath,
      previewUrl: `/preview/${projectId}`,
      createdAt: project.createdAt
    };

    console.log(`✅ Returned metadata for: ${projectId}`);
    res.json({ success: true, data: metadata });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

/**
 * @openapi
 * /projects:
 *   get:
 *     summary: Get user's projects
 *     tags: [Projects]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: List of user's projects
 */
app.get('/projects', authMiddleware, async (req, res) => {
  try {
    const projects = await Project.find({ userId: req.user.id }).sort('-createdAt');
    console.log(`✅ Returned ${projects.length} projects for user: ${req.user.username}`);

    res.json({
      success: true,
      data: projects.map(p => ({
        projectId: p.projectId,
        projectName: p.projectName || `Project ${p.projectId}`,
        websiteType: p.websiteType,
        features: p.features,
        modules: p.modules,
        createdAt: p.createdAt,
        previewUrl: `/preview/${p.projectId}`
      }))
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

app.get('/preview/:projectId', (req, res) => {
  try {
    const { projectId } = req.params;
    const projectDir = path.join(GENERATED_PROJECTS_DIR, projectId);

    if (!fs.existsSync(projectDir)) {
      return res.status(404).send('Project not found');
    }

    const metadata = PROJECTS_METADATA.get(projectId);
    const projectName = metadata?.projectName || projectId;
    const websiteType = metadata?.websiteType || 'basic';
    const features = metadata?.features || [];
    const modules = metadata?.modules || [];
    const structure = metadata?.structure || [];

    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Kyro Preview - ${projectName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
  <div class="min-h-screen p-8">
    <div class="max-w-4xl mx-auto">
      <div class="bg-white shadow rounded-lg p-6 mb-6">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">Kyro Preview</h1>
        <p class="text-gray-600">Project: ${projectName}</p>
      </div>

      <div class="bg-white shadow rounded-lg p-6 mb-6">
        <h2 class="text-xl font-semibold mb-4">Project Details</h2>
        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <p class="text-sm text-gray-600">Website Type</p>
            <p class="font-medium capitalize">${websiteType}</p>
          </div>
          <div>
            <p class="text-sm text-gray-600">Features</p>
            <p class="font-medium">${features.join(', ') || 'None'}</p>
          </div>
        </div>
        <div class="mb-4">
          <p class="text-sm text-gray-600 mb-2">Modules Generated</p>
          <div class="flex flex-wrap gap-2">
            ${modules.map(m => `<span class="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm">${m}</span>`).join('')}
          </div>
        </div>
      </div>

      <div class="bg-white shadow rounded-lg p-6">
        <h2 class="text-xl font-semibold mb-4">Project Structure</h2>
        <div class="bg-gray-50 p-4 rounded font-mono text-sm">
          ${structure.map(item => `<div class="py-1">📄 ${item}</div>`).join('')}
        </div>
      </div>

      <div class="mt-6 text-center">
        <a href="/download/${projectId}" class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 inline-block mr-3">
          Download Project
        </a>
        <a href="/dashboard" class="bg-gray-300 text-gray-700 px-6 py-2 rounded-lg hover:bg-gray-400 inline-block">
          Back to Dashboard
        </a>
      </div>
    </div>
  </div>
  <footer class="text-center py-4 text-gray-500 text-sm mt-8">
    Developed by Yasar Hameed
  </footer>
</body>
</html>
    `;

    res.send(html);
  } catch (error) {
    console.error('Preview error:', error);
    res.status(500).send('Internal server error');
  }
});

app.post('/project/:projectId/update', authMiddleware, async (req, res) => {
  try {
    const { projectId } = req.params;
    const { filePath, content } = req.body;

    if (!filePath || !content) {
      return res.status(400).json({ success: false, error: 'Missing filePath or content' });
    }

    // Security: prevent path traversal
    if (filePath.includes('..')) {
      return res.status(400).json({ success: false, error: 'Invalid file path' });
    }

    const projectPath = path.join(GENERATED_PROJECTS_DIR, projectId);
    const fullPath = path.join(projectPath, filePath);

    // Ensure the file is inside the project directory
    if (!fullPath.startsWith(projectPath)) {
      return res.status(400).json({ success: false, error: 'Invalid file path' });
    }

    if (!fs.existsSync(fullPath)) {
      return res.status(404).json({ success: false, error: 'File not found' });
    }

    fs.writeFileSync(fullPath, content, 'utf-8');
    console.log(`✅ File updated: ${fullPath}`);

    res.json({ success: true, message: 'File updated successfully' });
  } catch (error) {
    console.error('Update error:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

app.listen(PORT, () => {
  console.log(`Backend server running on http://localhost:${PORT}`);
  console.log(`Swagger docs available at http://localhost:${PORT}/api-docs`);
});
